---
idle:
  idle_exempt_roles:
  - admin
  - builder
  - coder
  - guest
  - idle_exempt
  monthly_reminder_cron:
    hour:
    - 15
    minute:
    - 0
    day:
    - 1
  monthly_reminder_title: Monthly Chores
  monthly_reminder: It's time to run the idle sweep!
  reminder_category: MISC
  use_roster: true
  idle_category: Announcements
  days_before_idle: 30
  arrivals_category: New Arrivals
  default_contact: Admin
  idle_warn_msg: You haven't played in awhile and your character is in danger of idling
    out.
  roster_arrival_msg: |-
    %{name} has been claimed off the roster.

    Position: %{position}

    RP Hooks:
    %{rp_hooks}
  roster_welcome_msg: Welcome!  You may wish to check your %xcnotes%xn and web portal
    profile page for any notes left by the prior player.  Type %xhonstage%xn to go
    forth and RP.
  roster_app_template: |-
    Please answer the following FIVE questions:


    **Tell us why you're picking this particular character?** (answer)


    **Is there anything about the background that you have questions about?**
    (answer)


    **Have you read our policies, timeline, and other important pages?** (answer)


    **How did you hear about our game?** (answer)


    **Please provide an email or discord info where you can be reached. Thank
    you!** (answer)
  roster_app_category: APP
  restrict_roster: true
  roster_fields:
  - field: name
    width: 20
    title: Name
  - field: demographic
    width: 10
    title: Alias
    value: alias
  - field: group
    width: 17
    title: Faction
    value: Faction
  - field: group
    width: 17
    title: Position
    value: Position
  shortcuts:
    idle/add: idle/action
    roster/update: roster/add
    roster/contact: roster/add
    roster/notes: roster/note
    idle/notes: idle/note
  permissions:
    manage_idle: Access idle purge commands.
    manage_roster: Access roster commands.